exclude: scripts/
default_stages: [commit, push]
default_language_version:
    python: python3.7
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        always_run: true
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.5.0
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        always_run: true
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
      always_run: true
-   repo:  https://github.com/timothycrosley/isort
    rev: 5.0.2
    hooks:
    -   id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
    types: [python]
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
        - id: black
          language_version: python3.7
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.780
    hooks:
    -   id: mypy
        exclude: ^(docs/|example-plugin/|tests/fixtures)
        always_run: true
